# Generated by Django 5.1 on 2026-06-17 01:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='レビューID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価')),
                ('comment', models.CharField(max_length=500, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soso.shoppingitem', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soso.accountuser', verbose_name='会員ID')),
            ],
            options={
                'db_table': 'shopping_review',
                'unique_together': {('item', 'user')},
            },
        ),
    ]
