# Generated by Django 5.1 on 2026-06-18 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TetrisPoint',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='soso.accountuser')),
                ('points', models.IntegerField(default=0, verbose_name='所持ポイント')),
                ('total_wins', models.IntegerField(default=0, verbose_name='勝利数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tetris_point',
            },
        ),
    ]
