# Generated by Django 5.1 on 2026-06-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soso.accountuser')),
            ],
            options={
                'db_table': 'gacha_history',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCoupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='クーポンコード')),
                ('discount_rate', models.IntegerField(verbose_name='割引率(%)')),
                ('rarity', models.CharField(max_length=20, verbose_name='レア度')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soso.accountuser')),
            ],
            options={
                'db_table': 'shopping_coupon',
            },
        ),
    ]
