# Generated by Django 5.1 on 2026-06-18 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soso', '0002_tetrispoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TetrisGachaHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('rarity', models.CharField(max_length=20, verbose_name='レア度')),
                ('discount_rate', models.IntegerField(verbose_name='割引率')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soso.accountuser')),
            ],
            options={
                'db_table': 'tetris_gacha_history',
            },
        ),
    ]
