# Generated by Django 5.1 on 2026-06-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soso', '0003_tetrisgachahistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('bet', models.IntegerField(verbose_name='ベット額')),
                ('payout', models.IntegerField(verbose_name='払戻額')),
                ('result', models.CharField(max_length=50, verbose_name='結果')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soso.accountuser')),
            ],
            options={
                'db_table': 'slot_history',
            },
        ),
    ]
